### ISSUE TITLE
Documentation missmatch

### ISSUE THREAD

**Issue by GeekEdem** [status-im/react-native-transparent-video#1]
Documentation missmatch.

You write use 
`yarn add react-native-transparent-video` and in code `react-native-transparent-video`, but package is `@status-im/react-native-transparent-video`, so must run
`yarn add @status-im/react-native-transparent-video` and `import TransparentVideo from "@status-im/react-native-transparent-video"`

**Comment by briansztamfater** [comment]
Thanks @GeekEdem, doc fixed
